version: '3.6'

networks:
  spark-network:
    name: spark-network
    ipam:
      config:
        - subnet: 172.0.0.0/24

services:
    nodemaster:
        container_name: nodemaster
        hostname: nodemaster
        command: master
        environment:
            - CLUSTER_NAME=test
        networks:
            spark-network:
                ipv4_address: 172.0.0.10
        volumes:
            - ./tasks/requirements.txt:/root/tasks/requirements.txt

    node2:
        container_name: node2
        hostname: node2
        command: node
        environment:
            - SPARK_MASTER=nodemaster:7077
            - SPARK_WORKER_CORES=1
            - SPARK_WORKER_MEMORY=2G
            - SPARK_DRIVER_MEMORY=512m
        networks:
            spark-network:
                ipv4_address: 172.0.0.2
        volumes:
            - ./tasks/requirements.txt:/root/tasks/requirements.txt

    node3:
        container_name: node3
        hostname: node3
        command: node
        environment:
            - SPARK_MASTER=nodemaster:7077
            - SPARK_WORKER_CORES=1
            - SPARK_WORKER_MEMORY=2G
            - SPARK_DRIVER_MEMORY=512m
        networks:
            spark-network:
                ipv4_address: 172.0.0.3
        volumes:
            - ./tasks/requirements.txt:/root/tasks/requirements.txt

    task:
        container_name: task
        hostname: task
        command: task
        environment:
            - SPARK_MASTER=nodemaster:7077
            - SPARK_EXECUTOR_MEMORY=2G
            - SPARK_EXECUTOR_CORES=1
        networks:
            - spark-network
        volumes:
        - ./tasks:/root/tasks

