version: '3.6'

services:
    nodemaster:
        image: mienkofax/spark-cluster:v0.8.1

    node2:
        image: mienkofax/spark-cluster:v0.8.1

    node3:
        image: mienkofax/spark-cluster:v0.8.1

    task:
        image: mienkofax/spark-cluster:v0.8.1
